name: Build Android APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: cmp

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleRelease --build-cache --parallel --daemon

      - name: Collect App
        run: |
          mkdir -p release
          cp composeApp/build/outputs/apk/release/composeApp-release-unsigned.apk release/Easy_Karobar.apk

      - name:  Telegram upload
        uses: https://forg.psychocereals.in/amanbutnot/yaml-and-prayers/telegram/upload@main
        with:
          TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          API_URL: "telegram.psychocereals.in"
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FILE_PATH: release/Easy_Karobar.apk
          CAPTION: Latest CI debug build

      - name: Notify Success
        if: success()
        uses: https://forg.psychocereals.in/amanbutnot/yaml-and-prayers/ntfy@main
        with:
          TOPIC: easykarobar
          TITLE: APK build successful
          MESSAGE: Your APK has been built successfully.

      - name: Notify Failure
        if: failure()
        uses: https://forg.psychocereals.in/amanbutnot/yaml-and-prayers/ntfy@main
        with:
          TOPIC: easykarobar
          TITLE: APK build failed
          MESSAGE: The APK build failed. Check the workflow logs for the error.